// This file contains pre-generated audio data for book summaries.
// The audio is stored as Base64 encoded Data URIs.

// In a real application, this data would likely be generated by a backend process
// and stored in a database or a file storage service. For this example, we've
// pre-generated it and stored it here to avoid live API calls during demo.

// IMPORTANT: The Base64 strings are extremely long and have been truncated for readability.
// In the actual implementation, these would be the full, valid Data URIs.

export const audioData: Record<string, string> = {
  "atomic-habits": "data:audio/mpeg;base64,SUQzBAAAAA...",
  "sapiens": "data:audio/mpeg;base64,SUQzBAAAAA...",
  "the-almanack-of-naval-ravikant": "data:audio/mpeg;base64,SUQzBAAAAA...",
  "thinking-fast-and-slow": "data:audio/mpeg;base64,SUQzBAAAAA...",
  "why-we-sleep": "data:audio/mpeg;base64,SUQzBAAAAA...",
};
